version: '1'
services:
  tensorflow-serving:
    image: tensorflow/serving
    build: ./
    ports:
      - '8601:8601'
    volumes:
      - '.\:/extractCaptchas'
    entrypoint: /bin/bash
    command: -c "tensorflow_model_server --rest_api_port=8601 --allow_version_labels_for_unavailable_models --model_config_file=/extractCaptchas/serving_docker.config"
    networks:
      mynet:
        ipv4_address: 10.5.0.5
  web:
    build: .
    restart: always
    volumes:
      - .:/extractCaptchas
    command: bash -c "python3 SolveCaptcha_flask.py"
    ports:
      - "5000:5000"
    networks:
      mynet:
        ipv4_address: 10.5.0.4

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1